### ISSUE TITLE
Weird track length behavior NERSC files

### ISSUE THREAD

**Issue by AsaNehm** [DUNE/dune-tms#113]
The performance plots for the track momentum/length reconstruction show a weird behavior
![Reco_tracklength_full](https://github.com/DUNE/dune-tms/assets/101250148/46c162b6-ae68-40e3-8929-332f33b5efbe)

**Comment by AsaNehm** [comment]
(full output file at /exp/dune/app/users/pnehm/output_UV_NERSC.txt)

**Comment by AsaNehm** [comment]
Checking for the truth for each iteration first if both hits are inside TMS (TMS_Geom::IsInsideTMS) seems to help
![Reco_tracklength](https://github.com/DUNE/dune-tms/assets/101250148/d0d80da3-21de-4f13-b7ad-6f59da203067)

**Comment by jdkio** [comment]
One thing I found is that the geometry gets corrupted somehow if it tries to measure a position far from the TMS. When that happens, all future calls are broken. This seems to be what's happening here. I fixed it by limiting the z in the world

The reason this happens with the nersc files specifically is because they have rock muons. The rock muons are more likely to reach this boundary where the corruption occurs

**Comment by AsaNehm** [comment]
Still a smaller 0 bin for the truth remains...

**Comment by AsaNehm** [comment]
For the full first NERSC samples 610 truth events have a density-weighted track length of exactly 0.
There are definitely also a non-negligible number of events where the reconstruction gets a considerable density-weighted track length while the truth stays at 0.
This seems to me like there is something bad going on with the truth

**Comment by AsaNehm** [comment]
I think this issue has been solved finally

**Comment by AsaNehm** [comment]
This was at least no longer observed in recent looks at the tracklength. There were changes to the truth information and changes to the reconstruction. Checked out with merge 135
